### ISSUE TITLE
"Connect With Slack" in settings does nothing

### ISSUE THREAD

**Issue by dkhokhlov** [scleriot/slack-reactions-notification#1]
"Connect With Slack" in settings does nothing
is it known issue?
![image](https://user-images.githubusercontent.com/7530150/159654267-7ca7468a-7774-421a-b4d1-1a50a35736f4.png)

**Comment by fredfies** [comment]
> "Connect With Slack" in settings does nothing is it known issue?"

It still doesn't work.. :-/

**Comment by maciej-skurznica** [comment]
I was wondering why mine doesn't work. Here is the answer 😝

**Comment by Manaaia** [comment]
Same here..

**Comment by scleriot** [comment]
Hey everyone,

this was an issue with the auth server, it's now fixed!

Let me know if that works again

**Comment by Manaaia** [comment]
It works! Thanks @scleriot :)

**Comment by camgatz87** [comment]
Hi @scleriot the issue is back, could you please take a look when feasible?

**Comment by scleriot** [comment]
Sorry for the issue, SSL cert was not renewing properly, it's back!

**Comment by camgatz87** [comment]
Hi @scleriot sorry to say that the issue is back again. I cannot deploy a slack app because of my organization's policy, so I depend on your server. Could you please take a look when it's convenient for you?

**Comment by sam272** [comment]
@scleriot any update on getting this issue resolved?

**Comment by ansgarschulte** [comment]
Still not working
